server:
  port: 11111

spring:
  application:
    name: DebeziumApp
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5556/source_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:29092