server:
  port: 8082

spring:
  application:
    name: DebeziumApp
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5556/destination_db
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092